import {
  Bed,
  CheckCircle,
  CigaretteOff,
  Clock,
  Coffee,
  ConciergeBell,
  CookingPot,
  Drama,
  Dumbbell,
  Fan,
  Home,
  Key,
  Lock,
  Luggage,
  Martini,
  ParkingCircle,
  PawPrint,
  Plane,
  ShowerHead,
  Sprout,
  Sun,
  SunDimIcon,
  Sunset,
  Thermometer,
  Tv,
  UserCheck,
  Users,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  WavesLadder,
  Wifi,
} from 'lucide-react';

const featureIconMap: Record<string, React.ElementType> = {
  '24h reception': Clock,
  'Air conditioning': Fan,
  'Airport shuttle': Plane,
  Balcony: Sun,
  Bar: Martini,
  'Breakfast available': Coffee,
  'Breakfast included': Coffee,
  'Coffee machine': Coffee,
  'Common room': Users,
  Concierge: ConciergeBell,
  'Daily housekeeping': Clock,
  'Entire place': Home,
  'Family-friendly': UserCheck,
  'Fitness center': Dumbbell,
  'Free Wi-Fi': Wifi,
  Garden: Sprout,
  Gym: Dumbbell,
  'Hostel entertainment': Drama,
  Kitchen: CookingPot,
  Lockers: Lock,
  'Luggage storage': Luggage,
  'Non-smoking rooms': CigaretteOff,
  Parking: ParkingCircle,
  'Pet-friendly': PawPrint,
  Pool: WavesLadder,
  'Private bathroom': ShowerHead,
  'Private beach': Sunset,
  'Private room': Bed,
  Restaurant: UtensilsCrossed,
  'Room service': Key,
  'Rooftop terrace': SunDimIcon,
  'Sea view': Waves,
  'Self check-in': Key,
  'Shared bathroom': ShowerHead,
  'Shared kitchen': CookingPot,
  Spa: Thermometer,
  TV: Tv,
  'TV in room': Tv,
  Terrace: Sun,
  'Tea/coffee maker': Coffee,
  Washer: WashingMachine,
  'Washing machine': WashingMachine,
};

export const getFeatureIcon = (feature: string): React.ElementType => {
  return featureIconMap[feature] || CheckCircle;
};
